# Acknowledgments

This book stands on the shoulders of giants.
In particular, these giants are the researchers working on Shapley values and SHAP, with a special mention of Scott Lundberg who played a pivotal role in bringing Shapley values to machine learning.

I would also like to thank all my beta readers for their invaluable feedback. In no particular order:
Carlos Mougan,
Bharat Raghunathan,
Junaid Butt,
Joshua Le Cornu,
Vaibhav Krishna Irugu Guruswamy,
Liban Mohamed,
Tim Triche,
Ronald Richman,
Germán García,
Jeff Herman,
Zachary Duey,
Sven Kruschel,
Joaquín Bogado,
Shino Chen
Sairam Subramanian,
Kerry Pearn,
Gavin Parnaby,
Robert Martin,
Andrea Ruggerini,
Arved Niklas Fanta,
Saman Parvaneh,
Simon Prince, 
Marouane Il Idrissi,
Kranthi Kamsanpalli,
Enrico Roletto,
David Cortés,
HaveF, and
Johannes Widera.

And of course a big thanks goes to Heidi, my wife, who always has to put up with my ramblings when I learn something new and just have to tell someone.
The cover art (the team of meerkats) was created by [jeeshiu from Fiverr](https://www.fiverr.com/jeeshiu).

