# The Role of Maskers (and Background Data)

Q that SHAP answers: Why did instance get a certain prediction?

This is answered contrastive to a distribution.


Q that SHAP answers: Why did instance get a certain prediction, rather than the average of the background data?

This comes from the background data which serves as reference distribution.

IN theory you could use a single data point.
TODO: Read https://arxiv.org/pdf/2105.13787.pdf

- determines, in combination with maskers, how absence of a feature is simulated
- not only technical
- but is also interesting and important point
- most of the times: use the same distribution as training
- background data defines:
  - the expected prediction which is the contrastive point
  - how absent features are simulated
-



TODO: simulations with CAlifornia data
- all data points as background
- one data point as background
- subset as background
- kmeans as background
-    

Special situations:

- Tree Explainer with feature_pertubation="tree_path_dependent"


Background data often assumed to be with independent features.


## The concept of maskers explained

- A technical concept to implement the idea of background data.
- A masker takes in a binary vector [0,1,...,1] (also called a binary mask)
- the 0's stand for the "absent" feature values and the 1's for the present ones
- so this is input encodes a coalition
- and the maskers job is to take a coalition and produce something that we can actually input into the model
- the output can even be multiple data points when we use the background data
- so the output can be a dataframe of points where the 0's are sampled from the background data
- then we input these data points from the makser to the model 
- we get the predictions and average them
- masker can be a function that does this mapping, but also directly an array or pandas.DataFrame, so a bit of a shortcut



Next chapter let's look at correlations and alternatives for the shapley values.

## Maskers


- Before we dive into other data structures like image and text, we have to talk about maskers
- maskers are a function that defines how coaliations are built
- maskers are the technical solution
- for the following problem: What does it mean for a feature value to be absent?
- because that highly depends on the data type
- for tabular data, absence is about drawing from background data
- for images this can be blurring out parts of the image
- and so on
- and this can be steered by providing maskers
-

List of maskers:

- Independent
- Partition
- Text
- Image


## Independent

- what we already know at this point
- features are just normal input features
- replacement is with background data
- arguments: data, max_samples


## Partition

- for the Partition Explainer
- like Indpendent, requires background data
- arguments: data, max_samples, clustering type
- data: the background data
- max_samples: how often to sample from background data for estimation
- clustering: distance metric for clustering the features


## Text

- For text input
- Tokenizes the text
- level of unit then becomes the token, not the characters.
- unless, of course, you tokenize on character level
- we will talk about this more in the text chapter (LINK)
- TODO: visualize this

## Image

-  for image data
-  masks out parts of the image. not pixels, but bigger portions
- more details in image chapter
- TODO: visualize how it works


