# Q&A


## What does option "XXX" for tree mean?


## How to speed up the computation?

There are many tips

- Use TreeSHAP, because much faster than Permutation or Kernel
- Use kmeans or sample for the background data. TODO: check how much
  - shap.kmeans(data, K) 
- For summary plots, use fewer data
-
-


## For DeepExplainer, how large should the backgroud data be?

100 is good, 1000 is very good

https://shap-lrjball.readthedocs.io/en/latest/generated/shap.DeepExplainer.html#shap.DeepExplainer.shap_values

## What software alternatives are available?

Shapley values are implemented in both the `iml` and [fastshap](https://github.com/bgreenwell/fastshap) packages for R.
In Julia, you can use [Shapley.jl](https://gitlab.com/ExpandingMan/Shapley.jl).

SHAP, an alternative estimation method for Shapley values, is presented in the [next chapter](#shap).

TODO: Add more to this list


## How do transformations of my features affect the Shapley value

- can't say that in general, because it depends on whether it changes the model as well
- but let's say the model stays the same, meaning same predictions for the same data points
- some examples where that's the case:
  - for monotonic transformations, decision trees will stay the same, just the cut at a different value, but which leads to the same partitioning of the data
  - for linear models, linear transformtions of the feature space won't affect the predictions
  - ...
- So if the features change, but the model predictions will stay the same, the Shapley values will stay the same as well
- INtuition: Shapley values are defined on the scale of the output
- Model is mostly treated as a black box
- 

