## Paying for the taxi

For now, forget about machine learning.
To motivate SHAP, we first have to understand Shapley values and will do so with a taxi ride example:
Alice, Bob, and Charlie had dinner together and now hail a taxi to get home.
They discuss what would be a fair way to share these costs of \$51.

Imagine we could know the cost of that ride for all possible combinations of Alice, Bob, and Charlie.
Only Alice takes the ride? That would be \$15.
Even though Alice and Charlie live together, adding Bob to the ride bumps the cost to \$25, because he insists of getting the luxury taxi.
Adding Bob to the Alice and Charlie makes the cost go up to \$51 since the Bob lives a bit further away. 
We can do this for all possible combinations and end up with the following table:


| Passengers           | Costs | Note                                  |
|----------------------|-------|--------------------------------------|
| {}                   |   $0  | No taxi ride, no costs               |
| {Alice}              |   $15 | Normal ride fare to Alice's & Bob's place |
| {Bob}                |   $25 | Bob always insists on getting luxury taxis |
| {Charlie}            |   $38 | Charlie lives a bit further away      |
| {Alice, Bob}         |   $25 | Bob always gets his way               |
| {Alice, Charlie}     |   $41 | Alice & Bob's place requires a slight detour |
| {Bob, Charlie}       |   $51 | Bob requires luxury, even when Charlie is there |
| {Alice, Bob, Charlie}|   $51 | The full fare with all 3 of them      |

This seems like a step in the right direction: With this table we get a first idea how much each person contributes to the cost of the ride.
But we have to get one step further by calculating the so-called marginal contributions of each person to each combination.
For example, how much additional cost does Alice contribute in the taxi ride together with Bob?

::: {.callout-note}

## Marginal Contribution

The marginal contribution of a player to a coalition is the value of the coalition *with* the player minus the value of the coalition *without* the player.

For the taxi ride example, the marginal contribution of a passenger to a set of other passengers is the cost included this passenger minus the cost excluding this passenger.

:::

With the help of the table, we can calculate marginal contributions.
We can compare the cost between {Alice,Bob} and {Bob}, which gives us how much Alice contributed to the {Alice,Bob}  taxi ride.
In this case, it's \$25 - \$25 = \$0, since the taxi ride doesn't get more expensive. 
If we calculate the marginal contribution for Bob to {Alice,Bob}, we get \$25 - \$15 = \$10, or in other words, adding Bob to a taxi ride with Alice adds \$10.
See where this is going?
We are going to do this for all possible marginal contributions:

| Adding              | To Coalition     | Cost Before | Cost After | Marginal Contribution |
|---------------------|------------------|-------------|------------|-----------------------|
| Alice             | {}               | $0          | $15        | $15                   |
| Alice             | {Bob}            | $25         | $25        | $0                    |
| Alice             | {Charlie}        | $38         | $41        | $3                    |
| Alice             | {Bob, Charlie}   | $51         | $51        | $0                    |
| Bob               | {}               | $0          | $25        | $25                   |
| Bob               | {Alice}          | $15         | $25        | $10                   |
| Bob               | {Charlie}        | $38         | $51        | $13                   |
| Bob               | {Alice, Charlie} | $41         | $51        | $10                   |
| Charlie           | {}               | $0          | $38        | $38                   |
| Charlie           | {Alice}          | $15         | $41        | $26                   |
| Charlie           | {Bob}            | $25         | $51        | $26                   |
| Charlie           | {Alice, Bob}     | $25         | $51        | $26                   |

TODO: Column 1: Adding. Column 2: To Coalition; Column 3: Cost Before; Column 4: Cost After; Column 5: Marginal Contribution

Again, feels like one step closer to a possible fair share of the ride costs.
Can we just average those marginal contributions per passenger?
We could, but that would make every marginal contribution get equal weight.
You can however, make the argument that adding, for example, Alice to an empty taxi is more informative than adding Alice to a taxi with Bob.
And this argument is about the order in which we can arrange the passengers.
There are 3!=6 possibilities of ordering the passengers:

- Alice, Bob, Charlie
- Alice, Charlie, Bob
- Bob, Alice, Charlie
- Bob, Charlie, Alice
- Charlie, Alice, Bob
- Charlie, Bob, Alice

In two of these cases, Alice was added to an empty taxi, but only in one case to a taxi with only Bob in it.
If we weight the marginal contributions accordingly, we get the following weighted average marginal contribution for Alice:

$$\frac{1}{2 + 1 + 1 + 2}(\underbrace{2 \cdot \$15}_{\text{Alice to empty}} + \underbrace{ 1 \cdot \$0}_{\text{Alice to Bob}} + \underbrace{1 \cdot \$3}_{\text{Alice to Charlie}} + \underbrace{2 \cdot \$0}_{\text{Alice to Bob,Charlie}})  = \$5.5$$

We divide by $\frac{1}{6}$ because 6 is the sum of the weights.
And that's our final answer for how much Alice should pay to the ride: \$5.5.

Likewise we can calculate the contribution for Bob:

$$\frac{1}{6}(\underbrace{2 \cdot \$25}_{\text{Bob to empty}} + \underbrace{ 1 \cdot \$10}_{\text{Bob to Alice}} + \underbrace{1 \cdot \$13}_{\text{Bob to Charlie}} + \underbrace{2 \cdot \$10}_{\text{Bob to Alice,Charlie}})  = \$15.5$$

And for Charlie:

$$\frac{1}{6}(\underbrace{2 \cdot \$38}_{\text{Charlie to empty}} + \underbrace{ 1 \cdot \$26}_{\text{Charlie to Alice}} + \underbrace{1 \cdot \$26}_{\text{Charlie to Bob}} + \underbrace{2 \cdot \$26}_{\text{Charlie to Alice,Bob}})  = \$30$$

The individual contributions add up to the total cost: \$5.5 + \$15.5 + \$30 = \$51. Neat.


As you might have guessed, this result is the Shapley values [@shapley1953value].
Shapley values are a method for fairly attributing the payout to each player in a coalition.
This method that comes from game theory requires to calculate for each combination of Alice, Bob, and Charlie how much the ride would have cost.
The method computing these attributions is called Shapley values, and according to this method, the above would be a fair share of the costs.

