# Theory of Shapley Values {#theory}

::: {.callout-tip appearance="simple"}

By the end of this chapter, you will be able to:

- Understand the theory of Shapley values.
- Calculate Shapley values for simple games.
- Understand the axioms of Shapley values: efficiency, symmetry, dummy, and additivity.

:::

To learn about SHAP, we first discuss the theory behind Shapley values from game theory.
We will progressively define a fair payout[^fair] in a coalition of players and ultimately arrive at Shapley values (spoiler alert).
[^fair]: There is no perfect definition of fairness everyone would agree upon. Shapley values define a very specific version of fairness, which can be seen as egalitarian. 

## Who's going to pay for that taxi?

Consider a concrete example that can be seen as a coalitional game: splitting the cost of a taxi ride.
Alice, Bob, and Charlie have dinner together and share a taxi ride home.
The total cost is \$51.
The question is, how should they divide the costs fairly?

View the taxi ride as a coalitional game:
Alice, Bob, and Charlie form a coalition and receive a specific payout.
In this case, the payout is negative (costs), but this doesn't change the fact that we can consider this as a coalitional game.
To determine a fair distribution of the costs, we first pose simpler questions:
How much would the ride cost for a random coalition of passengers?
For instance, how much would Alice pay for a taxi ride if she were alone?
How much would Alice and Bob pay if they shared a taxi?
Let's suppose it would be \$15 for Alice alone.
Alice and Bob live together, but adding Bob to the ride increases the cost to \$25, as he insists on a more spacious, luxurious taxi, adding a flat \$10 to the ride costs.
Adding Charlie to Alice and Bob's ride increases the cost to \$51 since Charlie lives somewhat further away. 
We define the taxi ride costs for all possible combinations and compile the following table:

| Passengers           | Cost | Note                                  |
|----------------------|-------|--------------------------------------|
| $\emptyset$          |   $0  | No taxi ride, no costs               |
| {Alice}              |   $15 | Standard fare to Alice's & Bob's place |
| {Bob}                |   $25 | Bob always insists on luxury taxis |
| {Charlie}            |   $38 | Charlie lives slightly further away      |
| {Alice, Bob}         |   $25 | Bob always gets his way               |
| {Alice, Charlie}     |   $41 | Alice & Bob's place requires a slight detour |
| {Bob, Charlie}       |   $51 | Bob is a creature of luxury and Charlie lives a bit further away|
| {Alice, Bob, Charlie}|   $51 | The full fare with all three of them      |

The coalition $\emptyset$ is a coalition without any players in it, i.e., an empty taxi.
This table seems like a step in the right direction, giving us an initial idea of how much each person contributes to the cost of the ride.

## Calculating marginal contributions for the taxi costs

We can take a step further by calculating the so-called marginal contributions of each passenger to each coalition.
For example, how much additional cost does Alice incur when she joins a taxi with Bob already in it?

::: {.callout-note}
## Marginal contribution
The marginal contribution of a player to a coalition is the value of the coalition *with* the player minus the value of the coalition *without* the player.
In the taxi example, the value of a coalition is equal to the cost of the ride as detailed in the above table.
Therefore, the marginal contribution of, for instance, Charlie to a taxi already containing Bob is the cost of the taxi with Bob and Charlie, minus the cost of the taxi with Bob alone. 

:::

Using the table, we can easily calculate the marginal contributions.
Taking an example, if we compare the cost between the {Alice, Bob} coalition and Bob alone, we derive the marginal contribution of Alice, the "player", to the coalition {Bob}.
In this scenario, it's \$25 - \$25 = \$0, as the taxi ride cost remains the same. 
If we calculate the marginal contribution of Bob to the {Alice} coalition, we get \$25 - \$15 = \$10, meaning adding Bob to a taxi ride with Alice increases the cost by \$10.
We calculate all possible marginal contributions in this way:

| Addition           | To Coalition     | Cost Before | Cost After | Marginal Contribution |
|---------------------|------------------|-------------|------------|-----------------------|
| Alice             | $\emptyset$      | $0          | $15        | $15                   |
| Alice             | {Bob}            | $25         | $25        | $0                    |
| Alice             | {Charlie}        | $38         | $41        | $3                    |
| Alice             | {Bob, Charlie}   | $51         | $51        | $0                    |
| Bob               | $\emptyset$      | $0          | $25        | $25                   |
| Bob               | {Alice}          | $15         | $25        | $10                   |
| Bob               | {Charlie}        | $38         | $51        | $13                   |
| Bob               | {Alice, Charlie} | $41         | $51        | $10                   |
| Charlie           | $\emptyset$      | $0          | $38        | $38                   |
| Charlie           | {Alice}          | $15         | $41        | $26                   |
| Charlie           | {Bob}            | $25         | $51        | $26                   |
| Charlie           | {Alice, Bob}     | $25         | $51        | $26                   |

We're one step closer to calculating a fair share of ride costs.
Could we just average these marginal contributions per passenger?
We could, but that would assign equal weight to every marginal contribution.
However, one could argue that we learn more about how much Alice should pay when we add her to an empty taxi compared to when we add her to a ride with Bob.
But how much more informative?

One way to answer this question is by considering all possible permutations of Alice, Bob, and Charlie.
There are $3!=3*2*1=6$ possible permutations of passengers:

- Alice, Bob, Charlie
- Alice, Charlie, Bob
- Bob, Alice, Charlie
- Charlie, Alice, Bob
- Bob, Charlie, Alice
- Charlie, Bob, Alice

We can use these permutations to form coalitions, for example, for Alice.
Each permutation then maps to a coalition:
People who come before Alice in the order are in the coalition, people after are not.
Since in a coalition the order of passengers doesn't matter, some coalitions will occur more often than others when we iterate through all permutations like this:
In 2 out of 6 permutations, Alice is added to an empty taxi;
In 1 out of 6, she is added to a taxi with Bob;
In 1 out of 6, she is added to a taxi with Charlie;
And in 2 out of 6, she is added to a taxi with both Bob and Charlie.
We use these counts to weight each marginal contribution to continue our journey towards a fair cost sharing.

We could make different decisions regarding how to "fairly" allocate the costs to the passengers.
For instance, we could weight the marginal contributions differently.
We could divide the cost by 3.
Alternatively, we could use solutions that depend on the order of passengers:
Alice alone would pay \$15, when we add Bob it's +\$10, which would be his share, and Charlie would pay the remainder.
However, all these different choices would lead us away from Shapley values.

## Averaging marginal contributions

In two of these cases, Alice was added to an empty taxi, and in one case, she was added to a taxi with only Bob.
By weighting the marginal contributions accordingly, we calculate the following weighted average marginal contribution for Alice, abbreviating Alice, Bob, and Charlie to A, B, and C:

$$\frac{1}{6}(\underbrace{2 \cdot \$15}_{\text{A to }\emptyset} + \underbrace{ 1 \cdot \$0}_{\text{A to B}} + \underbrace{1 \cdot \$3}_{\text{A to C}} + \underbrace{2 \cdot \$0}_{\text{A to B,C}})  = \$5.50$$

We multiply by $\frac{1}{6}$ because 6 is the sum of the weights (2 + 1 + 1 + 2).
That's how much Alice should pay for the ride: \$5.50.

We can calculate the contribution for Bob the same way:

$$\frac{1}{6}(\underbrace{2 \cdot \$25}_{\text{B to }\emptyset} + \underbrace{ 1 \cdot \$10}_{\text{B to A}} + \underbrace{1 \cdot \$13}_{\text{B to C}} + \underbrace{2 \cdot \$10}_{\text{B to A,C}})  = \$15.50$$

And for Charlie:

$$\frac{1}{6}(\underbrace{2 \cdot \$38}_{\text{C to }\emptyset} + \underbrace{ 1 \cdot \$26}_{\text{C to A}} + \underbrace{1 \cdot \$26}_{\text{C to B}} + \underbrace{2 \cdot \$26}_{\text{C to A,B}})  = \$30.00$$

The individual contributions sum to the total cost: \$5.50 + \$15.50 + \$30.00 = \$51.00. Perfect!
And that's it, this is how we compute Shapley values [@shapley1953value].

Let's formalize the taxi example in terms of game theory and explore the Shapley value theory, which makes Shapley values a unique solution.


## Calculating Shapley values

The upcoming sections will use several game theoretic terms.
Even though we've already used most of them in the previous example, here's an overview for reference.

| Term  | Math Term | Taxi Example |
|-------|------|--------------|
| Player | $1, \ldots, |N|$ | Passenger, for example Alice |
| Coalition of All Players | $N$ |  {Alice, Bob, Charlie}|
| Coalition | S | Any combination of passengers, ranging from $\emptyset$ to {Alice, Bob, Charlie}. |
| Size of a Coalition | $|S|$ | For example, $|\{\text{Alice}\}|=1$, $|\{\text{Alice}, \text{Bob}, \text{Charlie}\}|=3$ |
| Value Function | $v()$ | Defined by the table showing all possible arrangements of passengers in the taxi |
| Payout | v(N) | \$51, the cost of the taxi ride with all passengers |
|Shapley Value | $\phi_j$ | For example, $\phi_1=\$5.50$ for Alice, $\phi_2=\$15.50$ for Bob, and $\phi_3=\$30$ for Charlie. |

The value function $v$ can also be referred to as the characteristic function.

We have explored how to calculate Shapley values through the taxi ride example.
Now, let's formalize Shapley values for the general case:

$$
\phi_j = \sum_{S \subseteq N \backslash \{j\}} \frac{|S|!(N-|S|-1)!}{N!} (v(S \cup \{j\}) - v(S))
$$ {#eq-shapley} 

The value function $v: P(N) \mapsto \mathbb{R}$ maps from all possible coalitions of N players to a real number, which represents the payout for that coalition.
The formula is quite complex, so let's break it down.

- $v(S \cup \{j\}) - v(S)$: This is the core of the equation. It represents the marginal contribution of player $j$ to coalition $S$. If $j$ is Alice and $S=\{Bob\}$, then this part expresses how much more expensive the ride becomes when Alice joins Bob.
- $\sum_{S \subseteq N \backslash \{j\}}$: The entire formula is a sum over all possible coalitions without $j$. If we calculate the Shapley value for Alice, we sum over the coalitions: $\emptyset$, $\{Bob\}$, $\{Charlie\}$, and $\{Bob, Charlie\}$.
- $\frac{|S|!(N-|S|-1)!}{N!}$: This term determines the weight of a marginal contribution. $\emptyset$ and $N \backslash \{j\}$ get the highest weights. The $|N|!$ in the denominator ensures that the sum of the weights equals 1.

The complex formula isn't so intimidating after all!

::: {.callout-note}

## Shapley value formula summary

The Shapley value is the weighted average of a player's marginal contributions to all possible coalitions.

:::

## The axioms behind Shapley values

We now have the formula, but where did it come from?
Lloyd Shapley derived it [@shapley1953value], but it didn't just materialize out of thin air.
He proposed axioms defining what a fair distribution could look like, and from these axioms, he derived the formula.
Lloyd Shapley also proved that based on these axioms, the Shapley value formula yields a unique solution.

Let's discuss these axioms, namely **Efficiency**, **Symmetry**, **Dummy**, and **Additivity**.
An axiom is a statement accepted as self-evidently true. 
Consider the axioms as defining fairness when it comes to payouts in team play.

### Efficiency
The efficiency axiom states that the sum of the contributions must precisely add up to the payout.
This makes a lot of sense.
Consider Alice, Bob, and Charlie sharing a taxi ride and calculating their individual shares, but the contributions don't equal the total taxi fare.
All three, including the taxi driver, would find this method useless.
The efficiency axiom can be expressed formally as:

$$\sum_{j \in N}\phi_j = v(N)$$

### Symmetry

The symmetry principle states that if two players are identical, they should receive equal contributions.
Identical means that all their marginal contributions are the same.
For instance, if Bob wouldn't need the luxury version of the taxi, his marginal contributions would be exactly the same as Alice's.
The symmetry axiom says that in such situations, both should pay the same amount, which seems fair.

We can also express symmetry mathematically for two players $j$ and $k$:

If $v(S \cup \{j\}) = v(S \cup \{k\})$ for all $S \subseteq N \backslash \{j, k\}$, then $\phi_j = \phi_{k}$.

### Dummy or Null Player

The Shapley value for a player who doesn't contribute to any coalition is zero, which seems quite fair.
Let's introduce Dora, Charlie's dog, and consider her an additional player.
Assuming there's no extra cost for including Dora in any ride, all of Dora's marginal contributions would be \$0.
The dummy axiom states that when all marginal contributions are zero, the Shapley value should also be zero.
This rule seems reasonable, especially as Dora doesn't have any money.

To express this axiom formally:

If $v(S \cup \{j\}) = v(S)$ for all $S \subseteq N \backslash \{j\}$, then $\phi_j = 0$.

### Additivity

In a game with two value functions $v_1$ and $v_2$, the Shapley values for the sum of the games can be expressed as the sum of the Shapley values:

$$\phi_{j, v_1 + v_2} = \phi_{j, v_1} + \phi_{j, v_2}$$

Imagine Alice, Bob, and Charlie not only sharing a taxi but also going out for ice cream.
Their goal is to fairly divide not just the taxi costs, but both the taxi and ice cream costs.
The additivity axiom suggests that they could first calculate every persons fair share of the ice cream costs, then the taxi costs, and add them up per person.

These four[^fifth] axioms ensure the uniqueness of the Shapley values, indicating there's only one solution presented in the Shapley formula, @eq-shapley.
The proof of why this is the case won't be discussed in this book, as it would be too detailed.
Instead, it's time to relate this approach to explaining machine learning predictions.

[^fifth]: A fifth axiom called *Linearity* or *Marginality* exists, but it can be derived from the other axioms, so it doesn't introduce any new requirements for fair payouts.
